
CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY,
  USERID VARCHAR,
  EMAIL VARCHAR,
  USERNAME VARCHAR,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  ADDRESS1 VARCHAR,
  ADDRESS2 VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  ZIPCODE VARCHAR,
  PROFILE_IMAGE_URL VARCHAR,
  FACEBOOK_ID VARCHAR,
  TWITTER_ID VARCHAR
);
